# Generated by Django 4.1.5 on 2023-01-15 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Charity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charity_name', models.CharField(max_length=80)),
                ('total_volunteer', models.IntegerField(max_length=5)),
                ('monthly_donation', models.IntegerField(max_length=15)),
                ('email', models.EmailField(max_length=20)),
                ('phn_number', models.IntegerField(max_length=11)),
            ],
        ),
    ]
