# Generated by Django 4.1.5 on 2023-01-17 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0004_alter_charity_charity_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charity',
            name='charity_name',
            field=models.CharField(max_length=25),
        ),
    ]
